# Generated by Django 6.0.5 on 2026-05-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_userdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
