# Generated by Django 6.0.5 on 2026-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0004_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='email',
            field=models.CharField(default='temporary@email.com', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetail',
            name='role',
            field=models.CharField(default='applicant', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='requirements',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contactno',
            field=models.CharField(max_length=11),
        ),
    ]
