# Generated by Django 6.0.5 on 2026-05-27 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0006_alter_userdetail_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='firstname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
