# Generated by Django 6.0.5 on 2026-05-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0007_userdetail_firstname_userdetail_lastname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='password',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='username',
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='contactno',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='middlename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
