# Generated by Django 6.0.5 on 2026-05-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_remove_userdetail_firstname_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userdetail',
            name='middlename',
        ),
    ]
