# Generated by Django 6.0.5 on 2026-05-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0009_remove_userdetail_email_remove_userdetail_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='gender',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
