# Generated by Django 6.0.5 on 2026-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0010_alter_userdetail_birthdate_alter_userdetail_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(default='exit', upload_to='resumes/'),
            preserve_default=False,
        ),
    ]
