# Generated by Django 6.0.5 on 2026-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0011_application_status_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
