# Generated by Django 6.0.5 on 2026-05-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0012_alter_application_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='contactno',
            field=models.CharField(max_length=11),
        ),
    ]
